
trigger:
- main

pool:
  vmImage: ubuntu-latest
 

stages:
- stage: Build 
  jobs:
    - job: Firstjob
      steps:
        - bash: echo Build First job  
    - job: secondjob
      steps:
        - bash: echo Build second job
      
- stage: DevDeploy
  dependsOn: Build
  jobs:
    - job: DevDeployjob
      steps:
        - bash: echo DevDeploy job  
      
- stage: QADeploy
  dependsOn: Build
  jobs:
    - job: QADeploy 
      steps:
        - bash: echo QADeploy job
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy 
  jobs:
    - job: ProdDeploy 
      steps:
        - bash: echo ProdDeploy Job

       
         



